apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-helm-folder
spec:
  generators:
    - git:
        repoURL: https://github.com/avie-everc/argocd-example-apps.git
        revision: HEAD
        directories:
          - path: helm/*
  template:
    metadata:
      name: '{{path[0]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/avie-everc/argocd-example-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true